name: release-on-ubuntu

on:
  push:
    branches: [ feature/ubuntu-release ]

  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout from git
      uses: actions/checkout@v4
      with: 
        submodules: 'true'
    - name: Cache multiple paths
      uses: actions/cache@v4
      with:
        path: |
          ~/.ccache
          ~/perl5
        key: ${{ runner.os }}-cache3
    - name: Update apt 
      run: |
        sudo apt update
    - name: Install apt dependencies
      run: |
        sudo apt install -y build-essential bison flex libxml2-dev subversion zlib1g-dev m4 ragel re2c dos2unix texinfo texi2html gdb curl cpanminus ccache libboost-all-dev libmodern-perl-perl libyaml-perl liblocal-lib-perl libcapture-tiny-perl libpath-tiny-perl libtext-table-perl libdata-hexdump-perl libregexp-common-perl libclone-perl libfile-slurp-perl libgmp-dev
    - name: Install perl prerequisites
      run: |
        cpanm --local-lib=~/perl5 App::Prove Clone CPU::Z80::Assembler Data::Dump Data::HexDump File::Path List::Uniq Modern::Perl Object::Tiny::RW Regexp::Common Test::Harness Test::HexDifferences Text::Diff Text::Table YAML::Tiny
    - name: Build binaries
      run: |
        export BUILD_SDCC=1
        export BUILD_SDCC_HTTP=1
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        MAKE_CONCURRENCY=-j2 ./build.sh -pzx -pzxn
    - name: Generate tar-ball
      run: |
        strip bin/*
        cd ..
        tar cfz z88dk-ubuntu-22.04.tgz z88dk/bin z88dk/lib z88dk/include z88dk/libsrc/*.lib z88dk/libsrc/_DEVELOPMENT/*.[0-9]
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Automated release from ${{ github.ref_name }}"
        files: ../z88dk-ubuntu-22.04.tgz
